import { getCollection, type CollectionEntry } from 'astro:content';
import type { Locale } from '../i18n';

export const blogLocales: Locale[] = ['fr', 'en', 'es', 'de'];
export const postUrl = (post: CollectionEntry<'blog'>) => `/${post.data.locale}/blog/${post.id}/`;
export async function publishedPosts() {
  const posts = (await getCollection('blog')).filter(post => !post.data.draft && post.data.publishedAt <= new Date());
  const translations = new Set<string>();
  for (const post of posts) {
    if (!post.data.translationKey) continue;
    const key = `${post.data.locale}:${post.data.translationKey}`;
    if (translations.has(key)) throw new Error(`Duplicate blog translation: ${key}`);
    translations.add(key);
  }
  return posts.sort((a, b) => b.data.publishedAt.getTime() - a.data.publishedAt.getTime());
}
export const blogCopy = {
  fr: { home: 'Accueil', label: 'Le journal PubliTools', title: 'Votre savoir-faire mérite', accent: 'd’être vu.', lead: 'Des conseils concrets pour transformer vos chantiers en visibilité. Moins de théorie, plus de terrain.', latest: 'Les derniers articles', empty: 'Les bons conseils se préparent sur le terrain.', emptyText: 'Nos premiers guides sont en préparation : réseaux sociaux, visibilité locale et photos de chantier. Revenez bientôt découvrir le journal.', back: 'Découvrir PubliTools', read: 'Lire le guide', toc: 'Dans cet article', takeaways: 'L’essentiel à retenir', published: 'Publié le', updated: 'Mis à jour le', minutes: 'min de lecture', related: 'Pour aller plus loin', cta: 'Votre prochain contenu est déjà sur votre chantier.', ctaText: 'Transformez vos photos et vos vocaux en publications avec PubliTools.', button: 'Découvrir l’outil', subjects: { social: 'Réseaux sociaux', local: 'Visibilité locale', photos: 'Photos de chantier', ai: 'IA & productivité' } },
  en: { home: 'Home', label: 'The PubliTools journal', title: 'Your craftsmanship deserves', accent: 'to be seen.', lead: 'Practical advice to turn your jobsites into visibility. Less theory, more hands-on insight.', latest: 'Latest articles', empty: 'Good advice starts on the jobsite.', emptyText: 'Our first guides are on their way: social media, local visibility and jobsite photography. Come back soon to explore the journal.', back: 'Discover PubliTools', read: 'Read the guide', toc: 'In this article', takeaways: 'Key takeaways', published: 'Published on', updated: 'Updated on', minutes: 'min read', related: 'Keep exploring', cta: 'Your next post is already on your jobsite.', ctaText: 'Turn your photos and voice notes into posts with PubliTools.', button: 'Discover the tool', subjects: { social: 'Social media', local: 'Local visibility', photos: 'Jobsite photos', ai: 'AI & productivity' } },
  es: { home: 'Inicio', label: 'El blog de PubliTools', title: 'Tu trabajo merece', accent: 'ser visto.', lead: 'Consejos prácticos para convertir tus obras en visibilidad. Menos teoría, más experiencia de campo.', latest: 'Últimos artículos', empty: 'Los buenos consejos nacen en la obra.', emptyText: 'Estamos preparando nuestras primeras guías: redes sociales, visibilidad local y fotos de obra. Vuelve pronto para descubrirlas.', back: 'Descubrir PubliTools', read: 'Leer la guía', toc: 'En este artículo', takeaways: 'Puntos clave', published: 'Publicado el', updated: 'Actualizado el', minutes: 'min de lectura', related: 'Sigue explorando', cta: 'Tu próxima publicación ya está en tu obra.', ctaText: 'Convierte tus fotos y notas de voz en publicaciones con PubliTools.', button: 'Descubrir la herramienta', subjects: { social: 'Redes sociales', local: 'Visibilidad local', photos: 'Fotos de obra', ai: 'IA y productividad' } },
  de: { home: 'Startseite', label: 'Das PubliTools Journal', title: 'Ihr Handwerk verdient es,', accent: 'gesehen zu werden.', lead: 'Praktische Tipps, die Ihre Baustellen sichtbar machen. Weniger Theorie, mehr Praxis.', latest: 'Neueste Artikel', empty: 'Gute Tipps entstehen auf der Baustelle.', emptyText: 'Unsere ersten Ratgeber sind in Vorbereitung: Social Media, lokale Sichtbarkeit und Baustellenfotos. Schauen Sie bald wieder vorbei.', back: 'PubliTools entdecken', read: 'Ratgeber lesen', toc: 'In diesem Artikel', takeaways: 'Das Wichtigste im Überblick', published: 'Veröffentlicht am', updated: 'Aktualisiert am', minutes: 'Min. Lesezeit', related: 'Weiterlesen', cta: 'Ihr nächster Beitrag wartet auf Ihrer Baustelle.', ctaText: 'Machen Sie mit PubliTools aus Fotos und Sprachnachrichten fertige Beiträge.', button: 'Tool entdecken', subjects: { social: 'Social Media', local: 'Lokale Sichtbarkeit', photos: 'Baustellenfotos', ai: 'KI & Produktivität' } },
};
